import { createHighlighter } from "shiki";
import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { suggTheme } from "../src/lib/shiki-theme";
import { aiOutputCode, codeSamples } from "../src/lib/demo-code-samples";

const outDir = join(dirname(import.meta.dirname!), "src", "generated");
mkdirSync(outDir, { recursive: true });

const highlighter = await createHighlighter({ langs: ["ts"], themes: [suggTheme] });

const html = {
  aiDemo: highlighter.codeToHtml(aiOutputCode, { lang: "ts", theme: suggTheme }),
  bun: highlighter.codeToHtml(codeSamples.bun, { lang: "ts", theme: suggTheme }),
  git: highlighter.codeToHtml(codeSamples.git, { lang: "ts", theme: suggTheme }),
  npm: highlighter.codeToHtml(codeSamples.npm, { lang: "ts", theme: suggTheme }),
};

writeFileSync(
  join(outDir, "landing-code-html.ts"),
  `// Auto-generated by generate-landing-code.ts
export const aiDemoHtml = ${JSON.stringify(html.aiDemo)};
export const bunCodeHtml = ${JSON.stringify(html.bun)};
export const gitCodeHtml = ${JSON.stringify(html.git)};
export const npmCodeHtml = ${JSON.stringify(html.npm)};
`,
  "utf-8",
);

console.log("[generate-landing-code] Generated src/generated/landing-code-html.ts");
